name: Release

# Controls when the workflow will run
on:
  push:
    branches:    
      # Push events to branches matching refs/heads/release/*
      - 'release/**'
    paths:
      - '**'

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  validate-version:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | egrep -o '[[:digit:]].[[:digit:]].[[:digit:]]' -o)" >> $GITHUB_ENV
        
      - name: Print release version
        run: echo ${{ env.BRANCH_NAME }}

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
      
      - name: Version Check
        if: ${{ steps.project.outputs.version != env.BRANCH_NAME }}
        run: |
          echo "Branch version (${{ env.BRANCH_NAME }}) does not match pom.xml version (${{ steps.project.outputs.version }}). Please update pom version."
          exit 1
          
      - name: Version Check result
        if: ${{ steps.project.outputs.version == env.BRANCH_NAME }}
        run: |
          echo "Branch version (${{ env.BRANCH_NAME }}) match pom.xml version (${{ steps.project.outputs.version }})."
        
  static-analysis:
    needs: validate-version
    runs-on: ubuntu-latest

    steps:
      - name: static-analysis
        run: echo Running static-analysis

  unit-tests:
    needs: validate-version
    runs-on: ubuntu-latest

    steps:
      - name: unit-tests
        run: echo Running unit-tests
        
  build:
    needs: [static-analysis, unit-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          
      - name: Build
        run: |
          mvn package
          for f in ${{github.workspace}}/target/*.jar; do mv "$f" "$(echo "$f" | sed s/.jar/-RC-NNN.jar/)"; done
          echo "artifact_name=$(ls ${{github.workspace}}/target | grep jar)" >> $GITHUB_ENV
          echo "release_version=$(ls ${{github.workspace}}/target | grep jar | egrep -o '[[:digit:]].[[:digit:]].[[:digit:]]' -o)" >> $GITHUB_ENV
        
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact_name }}
          path: target/*.jar

  push-to-Quay:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy-to-DEV
        run: echo Push to Quay.io
        
  deploy-to-QA:
    needs: push-to-Quay
    runs-on: ubuntu-latest
    environment: 'QA'

    steps:
      - name: deploy-to-QA
        run: echo Deploy to QA

  deploy-to-UA:
    needs: push-to-Quay
    runs-on: ubuntu-latest
    environment: 'UA'

    steps:
      - name: deploy-to-UA
        run: echo Deploy to UA

generate-inmutable-version:
    needs: [deploy-to-QA, deploy-to-UA]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          
      - name: Build
        run: |
          mvn package
          echo "artifact_name=$(ls ${{github.workspace}}/target | grep jar)" >> $GITHUB_ENV
          echo "release_version=$(ls ${{github.workspace}}/target | grep jar | egrep -o '[[:digit:]].[[:digit:]].[[:digit:]]' -o)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact_name }}
          path: target/*.jar
      
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release_version }}
      
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
          draft: false
          prerelease: false
          
  deploy-to-PRO:
    needs: generate-inmutable-version
    runs-on: ubuntu-latest
    environment: 'PRO'

    steps:
      - name: deploy-to-PRO
        run: echo Deploy to PRO    
        
  tests:
    needs: deploy-to-PRO
    runs-on: ubuntu-latest

    steps:
      - name: tests
        run: echo Running tests    
        
  post:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: post
        run: echo Running post actions
