name: Snapshot

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  static-analysis:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: static-analysis
        run: echo Running static-analysis

  unit-tests:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: unit-tests
        run: echo Running unit-tests
        
  build:
    needs: [static-analysis, unit-tests]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          
      - name: Build SNAPSHOT
        run: |
          mvn package
          for f in ${{github.workspace}}/target/*.jar; do mv "$f" "$(echo "$f" | sed s/.jar/-SNAPSHOT.jar/)"; done
          echo "artifact_name=$(ls ${{github.workspace}}/target | grep jar)" >> $GITHUB_ENV    
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact_name }}
          path: target/*.jar

  deploy-to-DEV:
    needs: build
    runs-on: ubuntu-latest
    environment: 'DEV'

    steps:
      - name: deploy-to-DEV
        run: echo Deploy to DEV    
        
  tests:
    needs: deploy-to-DEV
    runs-on: ubuntu-latest

    steps:
      - name: tests
        run: echo Running tests    
        
  post:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: post
        run: echo Running post actions
